goods/urls.py
from django.urls import path
from goods import views
from goods.views import ProductsListView, ProductsDetailView, ProductsUpdateView,\
    ProductsCreateView, ProductsDeleteView

app_name = "goods"
urlpatterns = [
    path("", ProductsListView.as_view(), name="list"),
    path("goods/<int:pk>/", ProductsDetailView.as_view(), name="detail"),
    path("goods/update/<int:pk>/", ProductsUpdateView.as_view(), name="update"),
    path("goods/create/", ProductsCreateView.as_view(), name="create"),
    path("goods/delete/<int:pk>/", ProductsDeleteView.as_view(), name="delete"),
]

onlinestore/urls.py
from django.contrib import admin
from django.urls import path, include
from onlinestore import views
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('about/', TemplateView.as_view(template_name="about.html"), name="about"),
    path('', include('goods.urls')),
    path('', include('users.urls')),
    path('', TemplateView.as_view(template_name="homepage.html"), name="homepage"),
]

users/urls.py
from django.urls import path
from .views import CustomLoginView,\
    CustomLogoutView, CustomRegisterView, CustomDetailView, CustomEditView, CustomDeleteView

app_name = 'users'
urlpatterns = [
    path('login/', CustomLoginView.as_view(), name='login'),
    path('register/', CustomRegisterView.as_view(), name='register'),
    path('logout/', CustomLogoutView.as_view(), name='logout'),
    path('profile/<int:pk>/', CustomDetailView.as_view(), name='profile'),
    path('profile/edit/<int:pk>/', CustomEditView.as_view(), name='edit'),
    path('profile/delete/<int:pk>/', CustomDeleteView.as_view(), name='delete'),
]

goods/models.py
from django.db import models
from django.urls import reverse


class Categories(models.Model):
    slug = models.SlugField(max_length=32, unique=True)
    name = models.CharField(max_length=32)
    description = models.TextField(null=True, blank=True)
    product_img = models.ImageField(null=True, blank=True)

    def __str__(self):
        return f"{self.pk}. {self.name}"


class Products(models.Model):
    code = models.SlugField(max_length=32, unique=True)
    name = models.CharField(max_length=32)
    price = models.PositiveIntegerField(default=0)
    quantity = models.PositiveIntegerField(default=0)
    description = models.TextField(null=True, blank=True)
    product_img = models.ImageField(null=True, blank=True)
    category = models.ForeignKey(Categories, on_delete=models.PROTECT)

    class Meta:
        ordering = ['id']
        verbose_name = "Товар"
        verbose_name_plural = "Товары"

    def __str__(self):
        return f"{self.name}"

    def get_absolute_url(self):
        return reverse("goods:detail", kwargs={"slug": self.code})

users/models.py
"""
User application models
"""


from django.contrib.auth.models import AbstractUser


class CustomUserModel(AbstractUser):
    """Custom users model"""

    class Meta:
        db_table = "auth_user"
        verbose_name = "users"
        verbose_name_plural = "users"

goods/forms.py
from django import forms
from goods.models import Products


class CustomProductCreationForm(forms.ModelForm):
    class Meta:
        model = Products
        fields = "__all__"

users/forms.py
"""
Users application forms
"""

from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import CustomUserModel


class CustomUserCreationForm(UserCreationForm):

    class Meta:
        model = CustomUserModel
        fields = ("username", "email")


class CustomUserChangeForm(UserChangeForm):
    password = None

    class Meta:
        model = CustomUserModel
        fields = ("username", "email", "first_name", "last_name",)

goods/views.py
from goods.models import Products, Categories
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin
from .forms import CustomProductCreationForm


class ProductsListView(ListView):
    paginate_by = 4
    model = Products


class ProductsDetailView(DetailView):
    model = Products


class ProductsCreateView(CreateView):
    model = Products
    form_class = CustomProductCreationForm
    template_name = 'goods/products_create.html'
    success_url = '/'


class ProductsUpdateView(LoginRequiredMixin, UpdateView):
    model = Products
    fields = '__all__'
    success_url = '/'


class ProductsDeleteView(LoginRequiredMixin, DeleteView):
    model = Products
    template_name = "goods/products_confirm_delete.html"
    success_url = '/'

users/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView, LogoutView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import DetailView
from .forms import CustomUserCreationForm, CustomUserChangeForm
from .models import CustomUserModel


class CustomLoginView(LoginView):
    success_url = '/'
    template_name = 'users/user_login.html'

    def get_success_url(self):
        return self.success_url


class CustomRegisterView(CreateView):
    form_class = CustomUserCreationForm
    template_name = 'users/user_register.html'
    success_url = '/'


class CustomLogoutView(LoginRequiredMixin, LogoutView):
    next_page = '/'


class CustomDetailView(LoginRequiredMixin, DetailView):
    model = CustomUserModel
    template_name = 'users/user_profile.html'


class CustomEditView(LoginRequiredMixin, UpdateView):
    model = CustomUserModel
    form_class = CustomUserChangeForm
    template_name = 'users/user_profile_edit.html'
    success_url = '/'

    def get_success_url(self):
        return self.success_url


class CustomDeleteView(LoginRequiredMixin, DeleteView):
    model = CustomUserModel
    template_name = 'users/user_confirm_delete.html'
    success_url = '/'

goods/templates/goods/products_confirm_delete.html
{% extends "base.html" %}
{% block title %}Delete{% endblock %}
{% block container %}
    <form method="post">
        {% csrf_token %}
        <div>Ви впевнені, що бажаєте видалити {{object}}?</div>
        <input class="btn btn-success" type="Submit" value="Видалити">
        <a class="btn btn-success" href="{% url 'goods:list' %}">Скасувати</a>
    </form>
{% endblock %}

goods/templates/goods/products_create.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title %}"РтК" Новий товар{% endblock %}
{% block container %}
    <h2>Введіть дані для товару</h2>
    <form method="post">
      {% csrf_token %}
      {{ form|crispy }}
      <input class="btn btn-success" type="submit" value="Внести">
      <input class="btn btn-success" type="reset" value="Очистити">
      <a class="btn btn-success"  href="{% url 'homepage' %}" role="button">Скасувати</a>
    </form>
{% endblock %}

goods/templates/goods/products_detail.html
{% extends "base.html" %}
{% block container %}
    <h2>{{object.name}}</h2>
    <br>
    <br>
    Арт: {{ object.code }}
    Цена: {{ object.price }}
    <br>
    <br>
    <a class="btn btn-success" href="{% url 'goods:list' %}">B розробці</a>
    <a class="btn btn-success" href="{% url 'goods:list' %}">Назад</a>
{% endblock %}

goods/templates/goods/products_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block container %}
    <form method="post">
      {% csrf_token %}
      {{ form|crispy }}
      <input class="btn btn-success" type="submit" value="Прийняти">
      <input class="btn btn-success" type="reset" value="Очистити">
      <a class="btn btn-success"  href="{% url 'homepage' %}" role="button">Скасувати</a>
    </form>
{% endblock %}

goods/templates/goods/products_list.html
{% extends "base.html" %}
{% load static %}
{% block container %}
<div class="row row-cols-4">
  {% for object in object_list %}
    <div class="col mb-5">
      <div class="card" style="width: 18rem;">
        <img class="card-img-top" src="{% static '258184_original.jpg' %} " alt="goods/258184_original.jpg">
        <div class="card-body">
          <h5 class="card-title">{{ object.name }}</h5>
          <p class="card-text">Цена: {{ object.price }}</p>
        {% if object.quantity %}
          <p style="color: green">
          В наявності: {{ object.quantity }}
          </p>

          <a class="btn btn-success" href="{% url 'goods:detail' pk=object.pk %}">Купити</a>
          {% else %}
            <p style="color: red">
            Під замовлення
            </p>
            <a class="btn btn-success disabled"  href="{% url 'goods:detail' pk=object.pk %}">Купити</a>

        {% endif %}
        {% if user.is_staff %}
          <br>
          <br>
          <a class="btn btn-success" href="{% url 'goods:update' pk=object.pk %}">Редагувати</a>
          <a class="btn btn-success" href="{% url 'goods:delete' pk=object.pk %}">Видалити</a>
        {% endif %}
        </div>
      </div>
    </div>
  {% endfor %}

  </div>
  <div></div>
  {% if user.is_staff %}
    <a class="btn btn-success" href="{% url 'goods:create'%}">Додати новий товар</a>
  {% endif %}
{% if is_paginated %}
  <div class="card-footer text-end p-3">
      <ul class="pagination justify-content-center">
    {% if page_obj.has_previous %}
        <li><a class="page-link" href="?page={{ page_obj.previous_page_number }}">Previous</a></li>
    {% else %}
      <li class="page-item disabled">
      <span class="page-link">Previous</span>
    {% endif %}
    {% for i in page_obj.paginator.page_range %}
      {% if page_obj.number == i %}
            <li class="page-item active" aria-current="page">
                <span class="page-link">{{ i }}</span></li>
      {% else %}
        <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>


      {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
            <li class="page-item">
      <a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a></li>
    {% else %}
      <li class="page-item disabled">
      <span class="page-link">Next</span>
    {% endif %}
  </ul>
  </div>
  {% endif %}

{% endblock %}
<nav aria-label="Page navigation example">
  <ul class="pagination justify-content-center">
    <li class="page-item disabled">
      <a class="page-link" href="#" tabindex="-1" aria-disabled="true">Previous</a>
    </li>
    <li class="page-item"><a class="page-link" href="#">1</a></li>
    <li class="page-item"><a class="page-link" href="#">2</a></li>
    <li class="page-item"><a class="page-link" href="#">3</a></li>
    <li class="page-item">
      <a class="page-link" href="#">Next</a>
    </li>
  </ul>
</nav>

goods/templates/products/products_detail.html
{% extends "base.html" %}
{% block container %}
    {{ object }}

    <a href="{% url 'goods:update' slug=object.slug  %}">Edit</a>
    <a href="{% url 'goods:delete' slug=object.slug  %}">Delete</a>
{% endblock %}

goods/templates/products/products_list.html
{% extends "base.html" %}
{% load static %}
{% block container %}
<div class="row row-cols-4">
  {% for object in object_list %}
    <div class="col mb-5">
      <div class="card" style="width: 18rem;">
        <img class="card-img-top" src="{% static '258184_original.jpg' %} " alt="goods/258184_original.jpg">
        <div class="card-body">
          <h5 class="card-title">{{ object.name }}</h5>
          <p class="card-text">Цена: {{ object.price }}</p>
        {% if object.quantity %}
          <p style="color: green">
          В наявності: {{ object.quantity }}
          </p>

          <a class="btn btn-success" href="{% url 'goods:detail' slug=object.slug %}">Купити</a>
          {% else %}
            <p style="color: red">
            Під замовлення
            </p>
            <a class="btn btn-success disabled"  href="{% url 'goods:detail' slug=object.slug %}">Купити</a>

        {% endif %}
            </div>
      </div>
    </div>
  {% endfor %}
</div>
{% endblock %}

templates/_navbar.html
<nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark">
  <div class="collapse navbar-collapse ">
    <div>" "</div>
    <a class="navbar-brand" >Роги & копита</a>
    <div class="collapse navbar-collapse">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" href="{% url 'homepage' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'about' %}">About</a>
        </li>
      </ul>
    </div>
    <div class="collapse navbar-collapse justify-content-end">
      {% if user.is_authenticated %}
        <span class="text-light">
          {{ user }}
        </span>
        <div>" "</div>
        <a class="btn btn-success" href="{% url 'users:profile' pk=user.pk %}" role="button">Profile</a>
        <div>" "</div>
        <a class="btn btn-success" href="{% url 'users:logout' %}" role="button">Log Out</a>
        <div>" "</div>
      {% else %}
        <a class="btn btn-success" href="{% url 'users:login' %}" role="button">Log In</a>
        <div>" "</div>
        <a class="btn btn-success" href="{% url 'users:register' %}" role="button">Register</a>
        <div>" "</div>
      {% endif %}
    </div>
  </div>
</nav>

templates/about.html
{% extends "base.html" %}
{% block title %}"РтК" Про магазин{% endblock %}
{% block container %}
    <h2>
        «Роги та копита» (повна назва — «Чорноморське відділення Арбатівської контори із заготівлі рогів та копит»)
    </h2>
{% endblock %}

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" type="text/css" href="{% static 'onlinestore/css/bootstrap.css' %}" />
    <title>{% block title%}Default title{% endblock %}</title>
    <h1> Роги та копита </h1>
    {% include "_navbar.html" %}
    <br>
<body>
<div class="container">
    {% block container %}
    {% endblock %}
</div>

</body>
</html>

templates/homepage.html
{% extends "base.html" %}
{% block title %}"РтК" Головна{% endblock %}
{% block container %}
{% endblock %}

templates/index.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title%}Default title{% endblock %}</title>
    <h1> Роги та копита </h1>
    {% include "_navbar.html" %}
<body>
<div class="container">
    {% block container %}
    {% endblock %}
</div>

</body>
</html>

templates/product_about.html
{% extends "index.html" %}
{% block title %}{{ title }}{% endblock %}
{% block container %}
    <h1>{{ data.product }} </h1>
    <div>{{ data.description }}</div>
    <h2>Ціна: {{ data.price }} </h2>
    Наявність:
    {% if data.available %}
        <pr style="color:green">є в наявності</pr>
        <br><br>
        <input type="submit" value="Придбати">
    {% else %}
        <pr style="color:red">під замовлення</pr>
        <br><br>
        <input type="submit" value="Придбати" disabled>
    {% endif %}
 {% endblock %}

users/templates/signup.html
{% extends "base.html" %}
{% block title %}"РтК" Реєстрація{% endblock %}
{% block container %}
    <h2>Введіть дані для реєстрації</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
    <input type="Submit" value="Реєструватися">
    </form>
{% endblock %}

users/templates/users/user_confirm_delete.html
{% extends "base.html" %}
{% block title %}Delete{% endblock %}
{% block container %}
<form method="post">{% csrf_token %}
    <p>Ви впевнені, видалити користувача "{{object}}"?</p>
    <input class="btn btn-success" type="Submit" value="Видалити">
    <a class="btn btn-success"  href="{% url 'homepage' %}" role="button">Скасувати</a>
</form>
{% endblock %}

users/templates/users/user_login.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title %} Login Page{% endblock %}
{% block container %}
    <br>
    <h2>Введіть логін та пароль</h2>
    <br>
    <form method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <input class="btn btn-success" type="Submit" value="Увійти">
    </form>
{% endblock %}

users/templates/users/user_profile.html
{% extends "base.html" %}
{% block title %}"РтК" Головна{% endblock %}
{% block container %}
    <h2>
        Профіль користувача
    </h2>
    <div> <b>Логін: </b>{{ user }} </div>
    <div> <b>Ім'я: </b>{{ user.first_name }} </div>
    <div> <b>Прізвище: </b>{{ user.last_name }} </div>
    <div> <b>Email: </b>{{ user.email }} </div>
    <div> <b>Joined at: </b>{{ user.date_joined }} </div>
    <br>
    <a class="btn btn-success" href="{% url 'users:edit' pk=user.pk %}">Редагувати дані</a>
    <a class="btn btn-success" href="{% url 'users:delete' pk=user.pk %}">Вилучити</a>
    <hr>
    <div>
        <p>Всього замовлень: 0</p>
        <p>Виконано: 0</p>
        <p>На суму: 0</p>
        <p>Скасовано: 0</p>
    </div>

{% endblock %}

users/templates/users/user_profile_edit.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title %} Profile Edit Page{% endblock %}
{% block container %}
    <br>
    <h2>Ведіть дані</h2>
    <br>
    <form method="post">
        {% csrf_token %}
        {{ form|crispy }}
      <input class="btn btn-success" type="submit" value="Прийняти">
      <input class="btn btn-success" type="reset" value="Очистити">
      <a class="btn btn-success"  href="{% url 'homepage' %}" role="button">Скасувати</a>
    </form>
{% endblock %}

users/templates/users/user_register.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title %}"РтК" Реєстрація{% endblock %}
{% block container %}
    <h2>Введіть дані для реєстрації</h2>
    <form method="post">
      {% csrf_token %}
      {{ form|crispy }}
      <input class="btn btn-success" type="submit" value="Реєструватися">
      <input class="btn btn-success" type="reset" value="Очистити">
      <a class="btn btn-success"  href="{% url 'homepage' %}" role="button">Скасувати</a>
    </form>
{% endblock %}